spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 4197cf6adcf46baa56d8
            clientSecret: 3cd5ef4c70931fbe330479a1a3055844981f204b
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mybatis?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSL=false
    username: user
    password: P@ssW0rd
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl